/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_IMPORT = 1,
  anon_sym_AGENT = 2,
  anon_sym_SYSTEM = 3,
  anon_sym_EQ = 4,
  anon_sym_CONSTRAINTS = 5,
  anon_sym_NEVER = 6,
  anon_sym_MUST = 7,
  anon_sym_SHOULD = 8,
  anon_sym_AVOID = 9,
  anon_sym_MAY = 10,
  aux_sym_constraint_text_token1 = 11,
  anon_sym_FLOW = 12,
  anon_sym_TEST = 13,
  anon_sym_INPUT = 14,
  anon_sym_EXPECT = 15,
  anon_sym_NOT = 16,
  anon_sym_CONTAINS = 17,
  anon_sym_MATCHES = 18,
  sym_identifier = 19,
  sym_path = 20,
  sym_package = 21,
  anon_sym_DQUOTE = 22,
  sym_string_content = 23,
  sym_number = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  anon_sym_POUND = 27,
  aux_sym_comment_token1 = 28,
  sym__indent = 29,
  sym__dedent = 30,
  sym__newline = 31,
  sym_source_file = 32,
  sym__toplevel = 33,
  sym_import_statement = 34,
  sym_agent_declaration = 35,
  sym_agent_body = 36,
  sym__agent_member = 37,
  sym_system_directive = 38,
  sym_property = 39,
  sym__value = 40,
  sym_constraints_block = 41,
  sym_constraint = 42,
  sym_constraint_level = 43,
  sym_constraint_text = 44,
  sym_flow_block = 45,
  sym_flow_step = 46,
  sym_step_text = 47,
  sym_test_block = 48,
  sym__test_entry = 49,
  sym_test_input = 50,
  sym_test_expect = 51,
  sym_string = 52,
  sym_boolean = 53,
  sym_comment = 54,
  aux_sym_source_file_repeat1 = 55,
  aux_sym_agent_body_repeat1 = 56,
  aux_sym_constraints_block_repeat1 = 57,
  aux_sym_flow_block_repeat1 = 58,
  aux_sym_test_block_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_IMPORT] = "IMPORT",
  [anon_sym_AGENT] = "AGENT",
  [anon_sym_SYSTEM] = "SYSTEM",
  [anon_sym_EQ] = "=",
  [anon_sym_CONSTRAINTS] = "CONSTRAINTS",
  [anon_sym_NEVER] = "NEVER",
  [anon_sym_MUST] = "MUST",
  [anon_sym_SHOULD] = "SHOULD",
  [anon_sym_AVOID] = "AVOID",
  [anon_sym_MAY] = "MAY",
  [aux_sym_constraint_text_token1] = "constraint_text_token1",
  [anon_sym_FLOW] = "FLOW",
  [anon_sym_TEST] = "TEST",
  [anon_sym_INPUT] = "INPUT",
  [anon_sym_EXPECT] = "EXPECT",
  [anon_sym_NOT] = "NOT",
  [anon_sym_CONTAINS] = "CONTAINS",
  [anon_sym_MATCHES] = "MATCHES",
  [sym_identifier] = "identifier",
  [sym_path] = "path",
  [sym_package] = "package",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__toplevel] = "_toplevel",
  [sym_import_statement] = "import_statement",
  [sym_agent_declaration] = "agent_declaration",
  [sym_agent_body] = "agent_body",
  [sym__agent_member] = "_agent_member",
  [sym_system_directive] = "system_directive",
  [sym_property] = "property",
  [sym__value] = "_value",
  [sym_constraints_block] = "constraints_block",
  [sym_constraint] = "constraint",
  [sym_constraint_level] = "constraint_level",
  [sym_constraint_text] = "constraint_text",
  [sym_flow_block] = "flow_block",
  [sym_flow_step] = "flow_step",
  [sym_step_text] = "step_text",
  [sym_test_block] = "test_block",
  [sym__test_entry] = "_test_entry",
  [sym_test_input] = "test_input",
  [sym_test_expect] = "test_expect",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_agent_body_repeat1] = "agent_body_repeat1",
  [aux_sym_constraints_block_repeat1] = "constraints_block_repeat1",
  [aux_sym_flow_block_repeat1] = "flow_block_repeat1",
  [aux_sym_test_block_repeat1] = "test_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_IMPORT] = anon_sym_IMPORT,
  [anon_sym_AGENT] = anon_sym_AGENT,
  [anon_sym_SYSTEM] = anon_sym_SYSTEM,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_CONSTRAINTS] = anon_sym_CONSTRAINTS,
  [anon_sym_NEVER] = anon_sym_NEVER,
  [anon_sym_MUST] = anon_sym_MUST,
  [anon_sym_SHOULD] = anon_sym_SHOULD,
  [anon_sym_AVOID] = anon_sym_AVOID,
  [anon_sym_MAY] = anon_sym_MAY,
  [aux_sym_constraint_text_token1] = aux_sym_constraint_text_token1,
  [anon_sym_FLOW] = anon_sym_FLOW,
  [anon_sym_TEST] = anon_sym_TEST,
  [anon_sym_INPUT] = anon_sym_INPUT,
  [anon_sym_EXPECT] = anon_sym_EXPECT,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_CONTAINS] = anon_sym_CONTAINS,
  [anon_sym_MATCHES] = anon_sym_MATCHES,
  [sym_identifier] = sym_identifier,
  [sym_path] = sym_path,
  [sym_package] = sym_package,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__toplevel] = sym__toplevel,
  [sym_import_statement] = sym_import_statement,
  [sym_agent_declaration] = sym_agent_declaration,
  [sym_agent_body] = sym_agent_body,
  [sym__agent_member] = sym__agent_member,
  [sym_system_directive] = sym_system_directive,
  [sym_property] = sym_property,
  [sym__value] = sym__value,
  [sym_constraints_block] = sym_constraints_block,
  [sym_constraint] = sym_constraint,
  [sym_constraint_level] = sym_constraint_level,
  [sym_constraint_text] = sym_constraint_text,
  [sym_flow_block] = sym_flow_block,
  [sym_flow_step] = sym_flow_step,
  [sym_step_text] = sym_step_text,
  [sym_test_block] = sym_test_block,
  [sym__test_entry] = sym__test_entry,
  [sym_test_input] = sym_test_input,
  [sym_test_expect] = sym_test_expect,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_agent_body_repeat1] = aux_sym_agent_body_repeat1,
  [aux_sym_constraints_block_repeat1] = aux_sym_constraints_block_repeat1,
  [aux_sym_flow_block_repeat1] = aux_sym_flow_block_repeat1,
  [aux_sym_test_block_repeat1] = aux_sym_test_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_IMPORT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AGENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SYSTEM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONSTRAINTS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NEVER] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MUST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SHOULD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AVOID] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MAY] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constraint_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_FLOW] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TEST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INPUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EXPECT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONTAINS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MATCHES] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_package] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_body] = {
    .visible = true,
    .named = true,
  },
  [sym__agent_member] = {
    .visible = false,
    .named = true,
  },
  [sym_system_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_constraints_block] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_level] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_text] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_block] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_test_block] = {
    .visible = true,
    .named = true,
  },
  [sym__test_entry] = {
    .visible = false,
    .named = true,
  },
  [sym_test_input] = {
    .visible = true,
    .named = true,
  },
  [sym_test_expect] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_agent_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraints_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_test_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_path = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_path, 1},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 12,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 14,
  [32] = 32,
  [33] = 12,
  [34] = 34,
  [35] = 35,
  [36] = 12,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 44,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 51,
  [74] = 44,
  [75] = 44,
  [76] = 76,
  [77] = 63,
  [78] = 60,
  [79] = 60,
  [80] = 60,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 111,
        '#', 118,
        '-', 79,
        '.', 5,
        '=', 86,
        'A', 21,
        'C', 35,
        'E', 68,
        'F', 28,
        'I', 30,
        'M', 7,
        'N', 14,
        'S', 22,
        'T', 20,
        'f', 69,
        't', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(111);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0) ADVANCE(113);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(118);
      if (lookahead == 'S') ADVANCE(107);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(118);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(95);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '/') ADVANCE(109);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(109);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(53);
      if (lookahead == 'U') ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'C') ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(91);
      END_STATE();
    case 13:
      if (lookahead == 'D') ADVANCE(90);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(66);
      if (lookahead == 'O') ADVANCE(54);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(51);
      END_STATE();
    case 21:
      if (lookahead == 'G') ADVANCE(16);
      if (lookahead == 'V') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'H') ADVANCE(39);
      if (lookahead == 'Y') ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == 'H') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'I') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'I') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'L') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'M') ADVANCE(84);
      END_STATE();
    case 30:
      if (lookahead == 'M') ADVANCE(42);
      if (lookahead == 'N') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'N') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'N') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'N') ADVANCE(57);
      END_STATE();
    case 34:
      if (lookahead == 'N') ADVANCE(62);
      END_STATE();
    case 35:
      if (lookahead == 'O') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == 'O') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 'O') ADVANCE(67);
      END_STATE();
    case 38:
      if (lookahead == 'O') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 'O') ADVANCE(64);
      END_STATE();
    case 40:
      if (lookahead == 'P') ADVANCE(65);
      END_STATE();
    case 41:
      if (lookahead == 'P') ADVANCE(18);
      END_STATE();
    case 42:
      if (lookahead == 'P') ADVANCE(38);
      END_STATE();
    case 43:
      if (lookahead == 'R') ADVANCE(88);
      END_STATE();
    case 44:
      if (lookahead == 'R') ADVANCE(60);
      END_STATE();
    case 45:
      if (lookahead == 'R') ADVANCE(9);
      END_STATE();
    case 46:
      if (lookahead == 'S') ADVANCE(102);
      END_STATE();
    case 47:
      if (lookahead == 'S') ADVANCE(101);
      END_STATE();
    case 48:
      if (lookahead == 'S') ADVANCE(87);
      END_STATE();
    case 49:
      if (lookahead == 'S') ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == 'S') ADVANCE(63);
      END_STATE();
    case 51:
      if (lookahead == 'S') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == 'S') ADVANCE(61);
      if (lookahead == 'T') ADVANCE(8);
      END_STATE();
    case 53:
      if (lookahead == 'T') ADVANCE(10);
      if (lookahead == 'Y') ADVANCE(92);
      END_STATE();
    case 54:
      if (lookahead == 'T') ADVANCE(100);
      END_STATE();
    case 55:
      if (lookahead == 'T') ADVANCE(89);
      END_STATE();
    case 56:
      if (lookahead == 'T') ADVANCE(97);
      END_STATE();
    case 57:
      if (lookahead == 'T') ADVANCE(83);
      END_STATE();
    case 58:
      if (lookahead == 'T') ADVANCE(98);
      END_STATE();
    case 59:
      if (lookahead == 'T') ADVANCE(99);
      END_STATE();
    case 60:
      if (lookahead == 'T') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'T') ADVANCE(45);
      END_STATE();
    case 62:
      if (lookahead == 'T') ADVANCE(48);
      END_STATE();
    case 63:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 64:
      if (lookahead == 'U') ADVANCE(27);
      END_STATE();
    case 65:
      if (lookahead == 'U') ADVANCE(58);
      END_STATE();
    case 66:
      if (lookahead == 'V') ADVANCE(19);
      END_STATE();
    case 67:
      if (lookahead == 'W') ADVANCE(96);
      END_STATE();
    case 68:
      if (lookahead == 'X') ADVANCE(41);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 72:
      if (lookahead == 'l') ADVANCE(74);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 76:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(95);
      END_STATE();
    case 77:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 78:
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(113);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 80:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_IMPORT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_AGENT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_SYSTEM);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SYSTEM);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_CONSTRAINTS);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_NEVER);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_MUST);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_SHOULD);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_AVOID);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_MAY);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_constraint_text_token1);
      if (lookahead == '#') ADVANCE(118);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_constraint_text_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_constraint_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_FLOW);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_TEST);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_INPUT);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_EXPECT);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_CONTAINS);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_MATCHES);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Y') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_path);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_package);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(120);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 2, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 2, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 3, .external_lex_state = 2},
  [26] = {.lex_state = 3, .external_lex_state = 2},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 2, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 2, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 2, .external_lex_state = 2},
  [34] = {.lex_state = 3, .external_lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3, .external_lex_state = 2},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 76},
  [44] = {.lex_state = 0, .external_lex_state = 4},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 77},
  [47] = {.lex_state = 0, .external_lex_state = 4},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 4},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 0, .external_lex_state = 4},
  [52] = {.lex_state = 0, .external_lex_state = 4},
  [53] = {.lex_state = 0, .external_lex_state = 4},
  [54] = {.lex_state = 0, .external_lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 76},
  [60] = {.lex_state = 119},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 4},
  [66] = {.lex_state = 77},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 4},
  [69] = {.lex_state = 77},
  [70] = {.lex_state = 0, .external_lex_state = 4},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 0, .external_lex_state = 3},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 0, .external_lex_state = 4},
  [76] = {.lex_state = 0, .external_lex_state = 3},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 119},
  [79] = {.lex_state = 119},
  [80] = {.lex_state = 119},
  [81] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_IMPORT] = ACTIONS(1),
    [anon_sym_AGENT] = ACTIONS(1),
    [anon_sym_SYSTEM] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_CONSTRAINTS] = ACTIONS(1),
    [anon_sym_NEVER] = ACTIONS(1),
    [anon_sym_MUST] = ACTIONS(1),
    [anon_sym_SHOULD] = ACTIONS(1),
    [anon_sym_AVOID] = ACTIONS(1),
    [anon_sym_MAY] = ACTIONS(1),
    [anon_sym_FLOW] = ACTIONS(1),
    [anon_sym_TEST] = ACTIONS(1),
    [anon_sym_INPUT] = ACTIONS(1),
    [anon_sym_EXPECT] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_CONTAINS] = ACTIONS(1),
    [anon_sym_MATCHES] = ACTIONS(1),
    [sym_path] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__toplevel] = STATE(2),
    [sym_import_statement] = STATE(2),
    [sym_agent_declaration] = STATE(2),
    [sym_system_directive] = STATE(2),
    [sym_constraints_block] = STATE(2),
    [sym_flow_block] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_IMPORT] = ACTIONS(5),
    [anon_sym_AGENT] = ACTIONS(7),
    [anon_sym_SYSTEM] = ACTIONS(9),
    [anon_sym_CONSTRAINTS] = ACTIONS(11),
    [anon_sym_FLOW] = ACTIONS(13),
    [anon_sym_TEST] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_IMPORT,
    ACTIONS(7), 1,
      anon_sym_AGENT,
    ACTIONS(9), 1,
      anon_sym_SYSTEM,
    ACTIONS(11), 1,
      anon_sym_CONSTRAINTS,
    ACTIONS(13), 1,
      anon_sym_FLOW,
    ACTIONS(15), 1,
      anon_sym_TEST,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(3), 9,
      sym__toplevel,
      sym_import_statement,
      sym_agent_declaration,
      sym_system_directive,
      sym_constraints_block,
      sym_flow_block,
      sym_test_block,
      sym_comment,
      aux_sym_source_file_repeat1,
  [36] = 9,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_IMPORT,
    ACTIONS(26), 1,
      anon_sym_AGENT,
    ACTIONS(29), 1,
      anon_sym_SYSTEM,
    ACTIONS(32), 1,
      anon_sym_CONSTRAINTS,
    ACTIONS(35), 1,
      anon_sym_FLOW,
    ACTIONS(38), 1,
      anon_sym_TEST,
    ACTIONS(41), 1,
      anon_sym_POUND,
    STATE(3), 9,
      sym__toplevel,
      sym_import_statement,
      sym_agent_declaration,
      sym_system_directive,
      sym_constraints_block,
      sym_flow_block,
      sym_test_block,
      sym_comment,
      aux_sym_source_file_repeat1,
  [72] = 5,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(50), 1,
      sym__dedent,
    STATE(43), 1,
      sym_constraint_level,
    STATE(4), 3,
      sym_constraint,
      sym_comment,
      aux_sym_constraints_block_repeat1,
    ACTIONS(44), 5,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [94] = 5,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      sym__dedent,
    STATE(43), 1,
      sym_constraint_level,
    STATE(4), 3,
      sym_constraint,
      sym_comment,
      aux_sym_constraints_block_repeat1,
    ACTIONS(52), 5,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [116] = 3,
    ACTIONS(60), 1,
      sym__indent,
    STATE(18), 1,
      sym_agent_body,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [133] = 4,
    ACTIONS(54), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_constraint_level,
    STATE(5), 3,
      sym_constraint,
      sym_comment,
      aux_sym_constraints_block_repeat1,
    ACTIONS(52), 5,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [152] = 5,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      anon_sym_INPUT,
    ACTIONS(64), 1,
      anon_sym_EXPECT,
    ACTIONS(66), 1,
      sym__dedent,
    STATE(10), 5,
      sym__test_entry,
      sym_test_input,
      sym_test_expect,
      sym_comment,
      aux_sym_test_block_repeat1,
  [172] = 5,
    ACTIONS(68), 1,
      anon_sym_SYSTEM,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(74), 1,
      sym__dedent,
    STATE(11), 5,
      sym__agent_member,
      sym_system_directive,
      sym_property,
      sym_comment,
      aux_sym_agent_body_repeat1,
  [192] = 5,
    ACTIONS(76), 1,
      anon_sym_INPUT,
    ACTIONS(79), 1,
      anon_sym_EXPECT,
    ACTIONS(82), 1,
      anon_sym_POUND,
    ACTIONS(85), 1,
      sym__dedent,
    STATE(10), 5,
      sym__test_entry,
      sym_test_input,
      sym_test_expect,
      sym_comment,
      aux_sym_test_block_repeat1,
  [212] = 5,
    ACTIONS(87), 1,
      anon_sym_SYSTEM,
    ACTIONS(90), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_POUND,
    ACTIONS(96), 1,
      sym__dedent,
    STATE(11), 5,
      sym__agent_member,
      sym_system_directive,
      sym_property,
      sym_comment,
      aux_sym_agent_body_repeat1,
  [232] = 1,
    ACTIONS(98), 9,
      sym__dedent,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
      anon_sym_INPUT,
      anon_sym_EXPECT,
      anon_sym_POUND,
  [244] = 1,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [255] = 1,
    ACTIONS(102), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [266] = 4,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      anon_sym_INPUT,
    ACTIONS(64), 1,
      anon_sym_EXPECT,
    STATE(8), 5,
      sym__test_entry,
      sym_test_input,
      sym_test_expect,
      sym_comment,
      aux_sym_test_block_repeat1,
  [283] = 1,
    ACTIONS(98), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [294] = 4,
    ACTIONS(68), 1,
      anon_sym_SYSTEM,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_POUND,
    STATE(9), 5,
      sym__agent_member,
      sym_system_directive,
      sym_property,
      sym_comment,
      aux_sym_agent_body_repeat1,
  [311] = 1,
    ACTIONS(104), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [322] = 1,
    ACTIONS(106), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [333] = 1,
    ACTIONS(108), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [344] = 1,
    ACTIONS(110), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [355] = 4,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(112), 2,
      sym_path,
      sym_number,
    ACTIONS(116), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 3,
      sym__value,
      sym_string,
      sym_boolean,
  [372] = 1,
    ACTIONS(118), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      anon_sym_POUND,
  [383] = 1,
    ACTIONS(120), 7,
      sym__dedent,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
      anon_sym_POUND,
  [393] = 5,
    ACTIONS(122), 1,
      aux_sym_constraint_text_token1,
    ACTIONS(124), 1,
      anon_sym_POUND,
    ACTIONS(126), 1,
      sym__dedent,
    STATE(68), 1,
      sym_step_text,
    STATE(26), 3,
      sym_flow_step,
      sym_comment,
      aux_sym_flow_block_repeat1,
  [411] = 5,
    ACTIONS(128), 1,
      aux_sym_constraint_text_token1,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(134), 1,
      sym__dedent,
    STATE(68), 1,
      sym_step_text,
    STATE(26), 3,
      sym_flow_step,
      sym_comment,
      aux_sym_flow_block_repeat1,
  [429] = 4,
    ACTIONS(122), 1,
      aux_sym_constraint_text_token1,
    ACTIONS(124), 1,
      anon_sym_POUND,
    STATE(68), 1,
      sym_step_text,
    STATE(25), 3,
      sym_flow_step,
      sym_comment,
      aux_sym_flow_block_repeat1,
  [444] = 1,
    ACTIONS(136), 4,
      sym__dedent,
      anon_sym_INPUT,
      anon_sym_EXPECT,
      anon_sym_POUND,
  [451] = 2,
    ACTIONS(138), 2,
      anon_sym_SYSTEM,
      sym_identifier,
    ACTIONS(140), 2,
      sym__dedent,
      anon_sym_POUND,
  [460] = 1,
    ACTIONS(142), 4,
      sym__dedent,
      anon_sym_INPUT,
      anon_sym_EXPECT,
      anon_sym_POUND,
  [467] = 2,
    ACTIONS(102), 2,
      sym__dedent,
      anon_sym_POUND,
    ACTIONS(144), 2,
      anon_sym_SYSTEM,
      sym_identifier,
  [476] = 1,
    ACTIONS(146), 4,
      sym__dedent,
      anon_sym_INPUT,
      anon_sym_EXPECT,
      anon_sym_POUND,
  [483] = 2,
    ACTIONS(98), 2,
      sym__dedent,
      anon_sym_POUND,
    ACTIONS(148), 2,
      anon_sym_SYSTEM,
      sym_identifier,
  [492] = 2,
    ACTIONS(152), 1,
      sym__dedent,
    ACTIONS(150), 2,
      aux_sym_constraint_text_token1,
      anon_sym_POUND,
  [500] = 2,
    ACTIONS(154), 1,
      anon_sym_NOT,
    ACTIONS(156), 2,
      anon_sym_CONTAINS,
      anon_sym_MATCHES,
  [508] = 2,
    ACTIONS(98), 1,
      sym__dedent,
    ACTIONS(148), 2,
      aux_sym_constraint_text_token1,
      anon_sym_POUND,
  [516] = 2,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    ACTIONS(160), 1,
      sym_string_content,
  [523] = 2,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    STATE(81), 1,
      sym_string,
  [530] = 1,
    ACTIONS(162), 2,
      sym_path,
      sym_package,
  [535] = 1,
    ACTIONS(164), 2,
      anon_sym_CONTAINS,
      anon_sym_MATCHES,
  [540] = 2,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      sym_string,
  [547] = 2,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_string,
  [554] = 2,
    ACTIONS(166), 1,
      aux_sym_constraint_text_token1,
    STATE(50), 1,
      sym_constraint_text,
  [561] = 1,
    ACTIONS(168), 1,
      sym__newline,
  [565] = 1,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
  [569] = 1,
    ACTIONS(172), 1,
      sym_identifier,
  [573] = 1,
    ACTIONS(174), 1,
      sym__newline,
  [577] = 1,
    ACTIONS(176), 1,
      sym__newline,
  [581] = 1,
    ACTIONS(178), 1,
      sym__newline,
  [585] = 1,
    ACTIONS(180), 1,
      sym__newline,
  [589] = 1,
    ACTIONS(182), 1,
      sym__newline,
  [593] = 1,
    ACTIONS(184), 1,
      sym__newline,
  [597] = 1,
    ACTIONS(186), 1,
      sym__newline,
  [601] = 1,
    ACTIONS(188), 1,
      sym__indent,
  [605] = 1,
    ACTIONS(190), 1,
      anon_sym_EQ,
  [609] = 1,
    ACTIONS(192), 1,
      sym__newline,
  [613] = 1,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
  [617] = 1,
    ACTIONS(196), 1,
      sym__newline,
  [621] = 1,
    ACTIONS(198), 1,
      aux_sym_constraint_text_token1,
  [625] = 1,
    ACTIONS(200), 1,
      aux_sym_comment_token1,
  [629] = 1,
    ACTIONS(202), 1,
      sym__newline,
  [633] = 1,
    ACTIONS(204), 1,
      sym__newline,
  [637] = 1,
    ACTIONS(206), 1,
      sym_path,
  [641] = 1,
    ACTIONS(208), 1,
      sym__newline,
  [645] = 1,
    ACTIONS(210), 1,
      sym__newline,
  [649] = 1,
    ACTIONS(212), 1,
      sym_identifier,
  [653] = 1,
    ACTIONS(214), 1,
      sym__newline,
  [657] = 1,
    ACTIONS(216), 1,
      sym__newline,
  [661] = 1,
    ACTIONS(218), 1,
      sym_identifier,
  [665] = 1,
    ACTIONS(220), 1,
      sym__newline,
  [669] = 1,
    ACTIONS(222), 1,
      sym__newline,
  [673] = 1,
    ACTIONS(224), 1,
      sym__indent,
  [677] = 1,
    ACTIONS(226), 1,
      sym__newline,
  [681] = 1,
    ACTIONS(228), 1,
      sym__newline,
  [685] = 1,
    ACTIONS(230), 1,
      sym__newline,
  [689] = 1,
    ACTIONS(232), 1,
      sym__indent,
  [693] = 1,
    ACTIONS(234), 1,
      sym_path,
  [697] = 1,
    ACTIONS(236), 1,
      aux_sym_comment_token1,
  [701] = 1,
    ACTIONS(238), 1,
      aux_sym_comment_token1,
  [705] = 1,
    ACTIONS(240), 1,
      aux_sym_comment_token1,
  [709] = 1,
    ACTIONS(242), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 133,
  [SMALL_STATE(8)] = 152,
  [SMALL_STATE(9)] = 172,
  [SMALL_STATE(10)] = 192,
  [SMALL_STATE(11)] = 212,
  [SMALL_STATE(12)] = 232,
  [SMALL_STATE(13)] = 244,
  [SMALL_STATE(14)] = 255,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 283,
  [SMALL_STATE(17)] = 294,
  [SMALL_STATE(18)] = 311,
  [SMALL_STATE(19)] = 322,
  [SMALL_STATE(20)] = 333,
  [SMALL_STATE(21)] = 344,
  [SMALL_STATE(22)] = 355,
  [SMALL_STATE(23)] = 372,
  [SMALL_STATE(24)] = 383,
  [SMALL_STATE(25)] = 393,
  [SMALL_STATE(26)] = 411,
  [SMALL_STATE(27)] = 429,
  [SMALL_STATE(28)] = 444,
  [SMALL_STATE(29)] = 451,
  [SMALL_STATE(30)] = 460,
  [SMALL_STATE(31)] = 467,
  [SMALL_STATE(32)] = 476,
  [SMALL_STATE(33)] = 483,
  [SMALL_STATE(34)] = 492,
  [SMALL_STATE(35)] = 500,
  [SMALL_STATE(36)] = 508,
  [SMALL_STATE(37)] = 516,
  [SMALL_STATE(38)] = 523,
  [SMALL_STATE(39)] = 530,
  [SMALL_STATE(40)] = 535,
  [SMALL_STATE(41)] = 540,
  [SMALL_STATE(42)] = 547,
  [SMALL_STATE(43)] = 554,
  [SMALL_STATE(44)] = 561,
  [SMALL_STATE(45)] = 565,
  [SMALL_STATE(46)] = 569,
  [SMALL_STATE(47)] = 573,
  [SMALL_STATE(48)] = 577,
  [SMALL_STATE(49)] = 581,
  [SMALL_STATE(50)] = 585,
  [SMALL_STATE(51)] = 589,
  [SMALL_STATE(52)] = 593,
  [SMALL_STATE(53)] = 597,
  [SMALL_STATE(54)] = 601,
  [SMALL_STATE(55)] = 605,
  [SMALL_STATE(56)] = 609,
  [SMALL_STATE(57)] = 613,
  [SMALL_STATE(58)] = 617,
  [SMALL_STATE(59)] = 621,
  [SMALL_STATE(60)] = 625,
  [SMALL_STATE(61)] = 629,
  [SMALL_STATE(62)] = 633,
  [SMALL_STATE(63)] = 637,
  [SMALL_STATE(64)] = 641,
  [SMALL_STATE(65)] = 645,
  [SMALL_STATE(66)] = 649,
  [SMALL_STATE(67)] = 653,
  [SMALL_STATE(68)] = 657,
  [SMALL_STATE(69)] = 661,
  [SMALL_STATE(70)] = 665,
  [SMALL_STATE(71)] = 669,
  [SMALL_STATE(72)] = 673,
  [SMALL_STATE(73)] = 677,
  [SMALL_STATE(74)] = 681,
  [SMALL_STATE(75)] = 685,
  [SMALL_STATE(76)] = 689,
  [SMALL_STATE(77)] = 693,
  [SMALL_STATE(78)] = 697,
  [SMALL_STATE(79)] = 701,
  [SMALL_STATE(80)] = 705,
  [SMALL_STATE(81)] = 709,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraints_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraints_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraints_block_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_declaration, 3, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_directive, 3, 0, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_declaration, 4, 0, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_body, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraints_block, 6, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_block, 6, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_flow_block_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_flow_block_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_block_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_input, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_expect, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_system_directive, 3, 0, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_expect, 5, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_step, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_step, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [170] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_text, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_level, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_text, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_hmn_external_scanner_create(void);
void tree_sitter_hmn_external_scanner_destroy(void *);
bool tree_sitter_hmn_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_hmn_external_scanner_serialize(void *, char *);
void tree_sitter_hmn_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hmn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_hmn_external_scanner_create,
      tree_sitter_hmn_external_scanner_destroy,
      tree_sitter_hmn_external_scanner_scan,
      tree_sitter_hmn_external_scanner_serialize,
      tree_sitter_hmn_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "hmn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
