/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_IMPORT = 1,
  anon_sym_AGENT = 2,
  anon_sym_SYSTEM = 3,
  anon_sym_EQ = 4,
  anon_sym_CONSTRAINTS = 5,
  anon_sym_NEVER = 6,
  anon_sym_MUST = 7,
  anon_sym_SHOULD = 8,
  anon_sym_AVOID = 9,
  anon_sym_MAY = 10,
  aux_sym_constraint_text_token1 = 11,
  anon_sym_FLOW = 12,
  anon_sym_TEST = 13,
  anon_sym_INPUT = 14,
  anon_sym_EXPECT = 15,
  anon_sym_NOT = 16,
  anon_sym_CONTAINS = 17,
  anon_sym_MATCHES = 18,
  sym_identifier = 19,
  sym_path = 20,
  sym_package = 21,
  anon_sym_DQUOTE = 22,
  sym_string_content = 23,
  sym_number = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  aux_sym_comment_token1 = 27,
  aux_sym_comment_token2 = 28,
  sym__indent = 29,
  sym__dedent = 30,
  sym__newline = 31,
  sym_source_file = 32,
  sym__toplevel = 33,
  sym_import_statement = 34,
  sym_agent_declaration = 35,
  sym_agent_body = 36,
  sym__agent_member = 37,
  sym_system_directive = 38,
  sym_property = 39,
  sym__value = 40,
  sym_constraints_block = 41,
  sym_constraint = 42,
  sym_constraint_level = 43,
  sym_constraint_text = 44,
  sym_flow_block = 45,
  sym_flow_step = 46,
  sym_step_text = 47,
  sym_test_block = 48,
  sym__test_entry = 49,
  sym_test_input = 50,
  sym_test_expect = 51,
  sym_string = 52,
  sym_boolean = 53,
  sym_comment = 54,
  aux_sym_source_file_repeat1 = 55,
  aux_sym_agent_body_repeat1 = 56,
  aux_sym_constraints_block_repeat1 = 57,
  aux_sym_flow_block_repeat1 = 58,
  aux_sym_test_block_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_IMPORT] = "IMPORT",
  [anon_sym_AGENT] = "AGENT",
  [anon_sym_SYSTEM] = "SYSTEM",
  [anon_sym_EQ] = "=",
  [anon_sym_CONSTRAINTS] = "CONSTRAINTS",
  [anon_sym_NEVER] = "NEVER",
  [anon_sym_MUST] = "MUST",
  [anon_sym_SHOULD] = "SHOULD",
  [anon_sym_AVOID] = "AVOID",
  [anon_sym_MAY] = "MAY",
  [aux_sym_constraint_text_token1] = "constraint_text_token1",
  [anon_sym_FLOW] = "FLOW",
  [anon_sym_TEST] = "TEST",
  [anon_sym_INPUT] = "INPUT",
  [anon_sym_EXPECT] = "EXPECT",
  [anon_sym_NOT] = "NOT",
  [anon_sym_CONTAINS] = "CONTAINS",
  [anon_sym_MATCHES] = "MATCHES",
  [sym_identifier] = "identifier",
  [sym_path] = "path",
  [sym_package] = "package",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__toplevel] = "_toplevel",
  [sym_import_statement] = "import_statement",
  [sym_agent_declaration] = "agent_declaration",
  [sym_agent_body] = "agent_body",
  [sym__agent_member] = "_agent_member",
  [sym_system_directive] = "system_directive",
  [sym_property] = "property",
  [sym__value] = "_value",
  [sym_constraints_block] = "constraints_block",
  [sym_constraint] = "constraint",
  [sym_constraint_level] = "constraint_level",
  [sym_constraint_text] = "constraint_text",
  [sym_flow_block] = "flow_block",
  [sym_flow_step] = "flow_step",
  [sym_step_text] = "step_text",
  [sym_test_block] = "test_block",
  [sym__test_entry] = "_test_entry",
  [sym_test_input] = "test_input",
  [sym_test_expect] = "test_expect",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_agent_body_repeat1] = "agent_body_repeat1",
  [aux_sym_constraints_block_repeat1] = "constraints_block_repeat1",
  [aux_sym_flow_block_repeat1] = "flow_block_repeat1",
  [aux_sym_test_block_repeat1] = "test_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_IMPORT] = anon_sym_IMPORT,
  [anon_sym_AGENT] = anon_sym_AGENT,
  [anon_sym_SYSTEM] = anon_sym_SYSTEM,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_CONSTRAINTS] = anon_sym_CONSTRAINTS,
  [anon_sym_NEVER] = anon_sym_NEVER,
  [anon_sym_MUST] = anon_sym_MUST,
  [anon_sym_SHOULD] = anon_sym_SHOULD,
  [anon_sym_AVOID] = anon_sym_AVOID,
  [anon_sym_MAY] = anon_sym_MAY,
  [aux_sym_constraint_text_token1] = aux_sym_constraint_text_token1,
  [anon_sym_FLOW] = anon_sym_FLOW,
  [anon_sym_TEST] = anon_sym_TEST,
  [anon_sym_INPUT] = anon_sym_INPUT,
  [anon_sym_EXPECT] = anon_sym_EXPECT,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_CONTAINS] = anon_sym_CONTAINS,
  [anon_sym_MATCHES] = anon_sym_MATCHES,
  [sym_identifier] = sym_identifier,
  [sym_path] = sym_path,
  [sym_package] = sym_package,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__toplevel] = sym__toplevel,
  [sym_import_statement] = sym_import_statement,
  [sym_agent_declaration] = sym_agent_declaration,
  [sym_agent_body] = sym_agent_body,
  [sym__agent_member] = sym__agent_member,
  [sym_system_directive] = sym_system_directive,
  [sym_property] = sym_property,
  [sym__value] = sym__value,
  [sym_constraints_block] = sym_constraints_block,
  [sym_constraint] = sym_constraint,
  [sym_constraint_level] = sym_constraint_level,
  [sym_constraint_text] = sym_constraint_text,
  [sym_flow_block] = sym_flow_block,
  [sym_flow_step] = sym_flow_step,
  [sym_step_text] = sym_step_text,
  [sym_test_block] = sym_test_block,
  [sym__test_entry] = sym__test_entry,
  [sym_test_input] = sym_test_input,
  [sym_test_expect] = sym_test_expect,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_agent_body_repeat1] = aux_sym_agent_body_repeat1,
  [aux_sym_constraints_block_repeat1] = aux_sym_constraints_block_repeat1,
  [aux_sym_flow_block_repeat1] = aux_sym_flow_block_repeat1,
  [aux_sym_test_block_repeat1] = aux_sym_test_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_IMPORT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AGENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SYSTEM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONSTRAINTS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NEVER] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MUST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SHOULD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AVOID] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MAY] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constraint_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_FLOW] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TEST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INPUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EXPECT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONTAINS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MATCHES] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_package] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_body] = {
    .visible = true,
    .named = true,
  },
  [sym__agent_member] = {
    .visible = false,
    .named = true,
  },
  [sym_system_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_constraints_block] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_level] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_text] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_block] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_test_block] = {
    .visible = true,
    .named = true,
  },
  [sym__test_entry] = {
    .visible = false,
    .named = true,
  },
  [sym_test_input] = {
    .visible = true,
    .named = true,
  },
  [sym_test_expect] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_agent_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraints_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_test_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_path = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_path, 1},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 10,
  [29] = 11,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 51,
  [72] = 66,
  [73] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 110,
        '#', 117,
        '.', 4,
        '=', 86,
        'A', 20,
        'C', 34,
        'E', 68,
        'F', 27,
        'I', 29,
        'M', 6,
        'N', 13,
        'S', 21,
        'T', 19,
        'f', 69,
        't', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(110);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(117);
      if (lookahead == 'S') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '/') ADVANCE(108);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(108);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(53);
      if (lookahead == 'U') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'C') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(59);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(91);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(90);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(66);
      if (lookahead == 'O') ADVANCE(54);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(32);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(45);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(51);
      END_STATE();
    case 20:
      if (lookahead == 'G') ADVANCE(15);
      if (lookahead == 'V') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'H') ADVANCE(38);
      if (lookahead == 'Y') ADVANCE(50);
      END_STATE();
    case 22:
      if (lookahead == 'H') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'I') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(12);
      END_STATE();
    case 27:
      if (lookahead == 'L') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'M') ADVANCE(84);
      END_STATE();
    case 29:
      if (lookahead == 'M') ADVANCE(41);
      if (lookahead == 'N') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'N') ADVANCE(52);
      END_STATE();
    case 31:
      if (lookahead == 'N') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'N') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 'N') ADVANCE(62);
      END_STATE();
    case 34:
      if (lookahead == 'O') ADVANCE(30);
      END_STATE();
    case 35:
      if (lookahead == 'O') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'O') ADVANCE(67);
      END_STATE();
    case 37:
      if (lookahead == 'O') ADVANCE(43);
      END_STATE();
    case 38:
      if (lookahead == 'O') ADVANCE(64);
      END_STATE();
    case 39:
      if (lookahead == 'P') ADVANCE(65);
      END_STATE();
    case 40:
      if (lookahead == 'P') ADVANCE(17);
      END_STATE();
    case 41:
      if (lookahead == 'P') ADVANCE(37);
      END_STATE();
    case 42:
      if (lookahead == 'R') ADVANCE(88);
      END_STATE();
    case 43:
      if (lookahead == 'R') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 'R') ADVANCE(8);
      END_STATE();
    case 45:
      if (lookahead == 'S') ADVANCE(101);
      END_STATE();
    case 46:
      if (lookahead == 'S') ADVANCE(100);
      END_STATE();
    case 47:
      if (lookahead == 'S') ADVANCE(87);
      END_STATE();
    case 48:
      if (lookahead == 'S') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 49:
      if (lookahead == 'S') ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == 'S') ADVANCE(63);
      END_STATE();
    case 51:
      if (lookahead == 'S') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == 'S') ADVANCE(61);
      if (lookahead == 'T') ADVANCE(7);
      END_STATE();
    case 53:
      if (lookahead == 'T') ADVANCE(9);
      if (lookahead == 'Y') ADVANCE(92);
      END_STATE();
    case 54:
      if (lookahead == 'T') ADVANCE(99);
      END_STATE();
    case 55:
      if (lookahead == 'T') ADVANCE(89);
      END_STATE();
    case 56:
      if (lookahead == 'T') ADVANCE(96);
      END_STATE();
    case 57:
      if (lookahead == 'T') ADVANCE(83);
      END_STATE();
    case 58:
      if (lookahead == 'T') ADVANCE(97);
      END_STATE();
    case 59:
      if (lookahead == 'T') ADVANCE(98);
      END_STATE();
    case 60:
      if (lookahead == 'T') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'T') ADVANCE(44);
      END_STATE();
    case 62:
      if (lookahead == 'T') ADVANCE(47);
      END_STATE();
    case 63:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 64:
      if (lookahead == 'U') ADVANCE(26);
      END_STATE();
    case 65:
      if (lookahead == 'U') ADVANCE(58);
      END_STATE();
    case 66:
      if (lookahead == 'V') ADVANCE(18);
      END_STATE();
    case 67:
      if (lookahead == 'W') ADVANCE(95);
      END_STATE();
    case 68:
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 72:
      if (lookahead == 'l') ADVANCE(74);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 76:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(94);
      END_STATE();
    case 77:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 78:
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(112);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 80:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 110,
        '.', 4,
        '=', 86,
        'A', 20,
        'C', 34,
        'E', 68,
        'F', 27,
        'I', 29,
        'M', 6,
        'N', 13,
        'S', 21,
        'T', 19,
        'f', 69,
        't', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_IMPORT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_AGENT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_SYSTEM);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SYSTEM);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_CONSTRAINTS);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_NEVER);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_MUST);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_SHOULD);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_AVOID);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_MAY);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_constraint_text_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_constraint_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_FLOW);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_TEST);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_INPUT);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_EXPECT);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_CONTAINS);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_MATCHES);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Y') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_path);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_package);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(112);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(119);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 2, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 2, .external_lex_state = 3},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 76, .external_lex_state = 3},
  [25] = {.lex_state = 76, .external_lex_state = 3},
  [26] = {.lex_state = 2, .external_lex_state = 3},
  [27] = {.lex_state = 76},
  [28] = {.lex_state = 2, .external_lex_state = 3},
  [29] = {.lex_state = 2, .external_lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 76, .external_lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 76},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 77},
  [45] = {.lex_state = 77},
  [46] = {.lex_state = 0, .external_lex_state = 4},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 4},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 118},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 77},
  [54] = {.lex_state = 0, .external_lex_state = 4},
  [55] = {.lex_state = 0, .external_lex_state = 4},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 4},
  [66] = {.lex_state = 0, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0, .external_lex_state = 4},
  [70] = {.lex_state = 76},
  [71] = {.lex_state = 118},
  [72] = {.lex_state = 0, .external_lex_state = 4},
  [73] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_IMPORT] = ACTIONS(1),
    [anon_sym_AGENT] = ACTIONS(1),
    [anon_sym_SYSTEM] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_CONSTRAINTS] = ACTIONS(1),
    [anon_sym_NEVER] = ACTIONS(1),
    [anon_sym_MUST] = ACTIONS(1),
    [anon_sym_SHOULD] = ACTIONS(1),
    [anon_sym_AVOID] = ACTIONS(1),
    [anon_sym_MAY] = ACTIONS(1),
    [anon_sym_FLOW] = ACTIONS(1),
    [anon_sym_TEST] = ACTIONS(1),
    [anon_sym_INPUT] = ACTIONS(1),
    [anon_sym_EXPECT] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_CONTAINS] = ACTIONS(1),
    [anon_sym_MATCHES] = ACTIONS(1),
    [sym_path] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(52),
    [sym__toplevel] = STATE(2),
    [sym_import_statement] = STATE(2),
    [sym_agent_declaration] = STATE(2),
    [sym_system_directive] = STATE(2),
    [sym_constraints_block] = STATE(2),
    [sym_flow_block] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_IMPORT] = ACTIONS(5),
    [anon_sym_AGENT] = ACTIONS(7),
    [anon_sym_SYSTEM] = ACTIONS(9),
    [anon_sym_CONSTRAINTS] = ACTIONS(11),
    [anon_sym_FLOW] = ACTIONS(13),
    [anon_sym_TEST] = ACTIONS(15),
    [aux_sym_comment_token1] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_IMPORT,
    ACTIONS(7), 1,
      anon_sym_AGENT,
    ACTIONS(9), 1,
      anon_sym_SYSTEM,
    ACTIONS(11), 1,
      anon_sym_CONSTRAINTS,
    ACTIONS(13), 1,
      anon_sym_FLOW,
    ACTIONS(15), 1,
      anon_sym_TEST,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(3), 9,
      sym__toplevel,
      sym_import_statement,
      sym_agent_declaration,
      sym_system_directive,
      sym_constraints_block,
      sym_flow_block,
      sym_test_block,
      sym_comment,
      aux_sym_source_file_repeat1,
  [36] = 9,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_IMPORT,
    ACTIONS(26), 1,
      anon_sym_AGENT,
    ACTIONS(29), 1,
      anon_sym_SYSTEM,
    ACTIONS(32), 1,
      anon_sym_CONSTRAINTS,
    ACTIONS(35), 1,
      anon_sym_FLOW,
    ACTIONS(38), 1,
      anon_sym_TEST,
    ACTIONS(41), 1,
      aux_sym_comment_token1,
    STATE(3), 9,
      sym__toplevel,
      sym_import_statement,
      sym_agent_declaration,
      sym_system_directive,
      sym_constraints_block,
      sym_flow_block,
      sym_test_block,
      sym_comment,
      aux_sym_source_file_repeat1,
  [72] = 3,
    ACTIONS(46), 1,
      sym__indent,
    STATE(13), 1,
      sym_agent_body,
    ACTIONS(44), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [89] = 5,
    ACTIONS(48), 1,
      anon_sym_SYSTEM,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      aux_sym_comment_token1,
    ACTIONS(54), 1,
      sym__dedent,
    STATE(8), 5,
      sym__agent_member,
      sym_system_directive,
      sym_property,
      sym_comment,
      aux_sym_agent_body_repeat1,
  [109] = 4,
    ACTIONS(58), 1,
      sym__dedent,
    STATE(41), 1,
      sym_constraint_level,
    STATE(7), 2,
      sym_constraint,
      aux_sym_constraints_block_repeat1,
    ACTIONS(56), 5,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [127] = 4,
    ACTIONS(63), 1,
      sym__dedent,
    STATE(41), 1,
      sym_constraint_level,
    STATE(7), 2,
      sym_constraint,
      aux_sym_constraints_block_repeat1,
    ACTIONS(60), 5,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [145] = 5,
    ACTIONS(65), 1,
      anon_sym_SYSTEM,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(71), 1,
      aux_sym_comment_token1,
    ACTIONS(74), 1,
      sym__dedent,
    STATE(8), 5,
      sym__agent_member,
      sym_system_directive,
      sym_property,
      sym_comment,
      aux_sym_agent_body_repeat1,
  [165] = 1,
    ACTIONS(76), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [176] = 1,
    ACTIONS(78), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [187] = 1,
    ACTIONS(80), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [198] = 4,
    ACTIONS(48), 1,
      anon_sym_SYSTEM,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      aux_sym_comment_token1,
    STATE(5), 5,
      sym__agent_member,
      sym_system_directive,
      sym_property,
      sym_comment,
      aux_sym_agent_body_repeat1,
  [215] = 1,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [226] = 3,
    STATE(41), 1,
      sym_constraint_level,
    STATE(6), 2,
      sym_constraint,
      aux_sym_constraints_block_repeat1,
    ACTIONS(56), 5,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [241] = 4,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 2,
      sym_path,
      sym_number,
    ACTIONS(88), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 3,
      sym__value,
      sym_string,
      sym_boolean,
  [258] = 1,
    ACTIONS(90), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [269] = 1,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [280] = 1,
    ACTIONS(94), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [291] = 1,
    ACTIONS(96), 8,
      ts_builtin_sym_end,
      anon_sym_IMPORT,
      anon_sym_AGENT,
      anon_sym_SYSTEM,
      anon_sym_CONSTRAINTS,
      anon_sym_FLOW,
      anon_sym_TEST,
      aux_sym_comment_token1,
  [302] = 4,
    ACTIONS(98), 1,
      anon_sym_INPUT,
    ACTIONS(100), 1,
      anon_sym_EXPECT,
    ACTIONS(102), 1,
      sym__dedent,
    STATE(21), 4,
      sym__test_entry,
      sym_test_input,
      sym_test_expect,
      aux_sym_test_block_repeat1,
  [318] = 4,
    ACTIONS(104), 1,
      anon_sym_INPUT,
    ACTIONS(107), 1,
      anon_sym_EXPECT,
    ACTIONS(110), 1,
      sym__dedent,
    STATE(21), 4,
      sym__test_entry,
      sym_test_input,
      sym_test_expect,
      aux_sym_test_block_repeat1,
  [334] = 1,
    ACTIONS(112), 6,
      sym__dedent,
      anon_sym_NEVER,
      anon_sym_MUST,
      anon_sym_SHOULD,
      anon_sym_AVOID,
      anon_sym_MAY,
  [343] = 3,
    ACTIONS(98), 1,
      anon_sym_INPUT,
    ACTIONS(100), 1,
      anon_sym_EXPECT,
    STATE(20), 4,
      sym__test_entry,
      sym_test_input,
      sym_test_expect,
      aux_sym_test_block_repeat1,
  [356] = 4,
    ACTIONS(114), 1,
      aux_sym_constraint_text_token1,
    ACTIONS(116), 1,
      sym__dedent,
    STATE(63), 1,
      sym_step_text,
    STATE(25), 2,
      sym_flow_step,
      aux_sym_flow_block_repeat1,
  [370] = 4,
    ACTIONS(118), 1,
      aux_sym_constraint_text_token1,
    ACTIONS(121), 1,
      sym__dedent,
    STATE(63), 1,
      sym_step_text,
    STATE(25), 2,
      sym_flow_step,
      aux_sym_flow_block_repeat1,
  [384] = 2,
    ACTIONS(123), 2,
      anon_sym_SYSTEM,
      sym_identifier,
    ACTIONS(125), 2,
      sym__dedent,
      aux_sym_comment_token1,
  [393] = 3,
    ACTIONS(114), 1,
      aux_sym_constraint_text_token1,
    STATE(63), 1,
      sym_step_text,
    STATE(24), 2,
      sym_flow_step,
      aux_sym_flow_block_repeat1,
  [404] = 2,
    ACTIONS(78), 2,
      sym__dedent,
      aux_sym_comment_token1,
    ACTIONS(127), 2,
      anon_sym_SYSTEM,
      sym_identifier,
  [413] = 2,
    ACTIONS(80), 2,
      sym__dedent,
      aux_sym_comment_token1,
    ACTIONS(129), 2,
      anon_sym_SYSTEM,
      sym_identifier,
  [422] = 2,
    ACTIONS(131), 1,
      anon_sym_NOT,
    ACTIONS(133), 2,
      anon_sym_CONTAINS,
      anon_sym_MATCHES,
  [430] = 1,
    ACTIONS(135), 3,
      sym__dedent,
      anon_sym_INPUT,
      anon_sym_EXPECT,
  [436] = 1,
    ACTIONS(137), 3,
      sym__dedent,
      anon_sym_INPUT,
      anon_sym_EXPECT,
  [442] = 1,
    ACTIONS(139), 3,
      sym__dedent,
      anon_sym_INPUT,
      anon_sym_EXPECT,
  [448] = 2,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      sym_string,
  [455] = 2,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      sym_string,
  [462] = 2,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      sym_string_content,
  [469] = 1,
    ACTIONS(145), 2,
      anon_sym_CONTAINS,
      anon_sym_MATCHES,
  [474] = 1,
    ACTIONS(147), 2,
      sym__dedent,
      aux_sym_constraint_text_token1,
  [479] = 1,
    ACTIONS(149), 2,
      sym_path,
      sym_package,
  [484] = 2,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_string,
  [491] = 2,
    ACTIONS(151), 1,
      aux_sym_constraint_text_token1,
    STATE(50), 1,
      sym_constraint_text,
  [498] = 1,
    ACTIONS(153), 1,
      sym__indent,
  [502] = 1,
    ACTIONS(155), 1,
      sym_path,
  [506] = 1,
    ACTIONS(157), 1,
      sym_identifier,
  [510] = 1,
    ACTIONS(159), 1,
      sym_identifier,
  [514] = 1,
    ACTIONS(161), 1,
      sym__newline,
  [518] = 1,
    ACTIONS(163), 1,
      sym__indent,
  [522] = 1,
    ACTIONS(165), 1,
      sym__indent,
  [526] = 1,
    ACTIONS(167), 1,
      sym__newline,
  [530] = 1,
    ACTIONS(169), 1,
      sym__newline,
  [534] = 1,
    ACTIONS(171), 1,
      aux_sym_comment_token2,
  [538] = 1,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
  [542] = 1,
    ACTIONS(175), 1,
      sym_identifier,
  [546] = 1,
    ACTIONS(177), 1,
      sym__newline,
  [550] = 1,
    ACTIONS(179), 1,
      sym__newline,
  [554] = 1,
    ACTIONS(181), 1,
      sym__newline,
  [558] = 1,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
  [562] = 1,
    ACTIONS(185), 1,
      sym__newline,
  [566] = 1,
    ACTIONS(187), 1,
      sym__newline,
  [570] = 1,
    ACTIONS(189), 1,
      sym__newline,
  [574] = 1,
    ACTIONS(191), 1,
      sym__newline,
  [578] = 1,
    ACTIONS(193), 1,
      sym__newline,
  [582] = 1,
    ACTIONS(195), 1,
      sym__newline,
  [586] = 1,
    ACTIONS(197), 1,
      sym__newline,
  [590] = 1,
    ACTIONS(199), 1,
      sym__newline,
  [594] = 1,
    ACTIONS(201), 1,
      sym__newline,
  [598] = 1,
    ACTIONS(203), 1,
      sym__newline,
  [602] = 1,
    ACTIONS(205), 1,
      anon_sym_EQ,
  [606] = 1,
    ACTIONS(207), 1,
      sym__newline,
  [610] = 1,
    ACTIONS(209), 1,
      aux_sym_constraint_text_token1,
  [614] = 1,
    ACTIONS(211), 1,
      aux_sym_comment_token2,
  [618] = 1,
    ACTIONS(213), 1,
      sym__newline,
  [622] = 1,
    ACTIONS(215), 1,
      sym_path,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 89,
  [SMALL_STATE(6)] = 109,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 145,
  [SMALL_STATE(9)] = 165,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 187,
  [SMALL_STATE(12)] = 198,
  [SMALL_STATE(13)] = 215,
  [SMALL_STATE(14)] = 226,
  [SMALL_STATE(15)] = 241,
  [SMALL_STATE(16)] = 258,
  [SMALL_STATE(17)] = 269,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 291,
  [SMALL_STATE(20)] = 302,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 334,
  [SMALL_STATE(23)] = 343,
  [SMALL_STATE(24)] = 356,
  [SMALL_STATE(25)] = 370,
  [SMALL_STATE(26)] = 384,
  [SMALL_STATE(27)] = 393,
  [SMALL_STATE(28)] = 404,
  [SMALL_STATE(29)] = 413,
  [SMALL_STATE(30)] = 422,
  [SMALL_STATE(31)] = 430,
  [SMALL_STATE(32)] = 436,
  [SMALL_STATE(33)] = 442,
  [SMALL_STATE(34)] = 448,
  [SMALL_STATE(35)] = 455,
  [SMALL_STATE(36)] = 462,
  [SMALL_STATE(37)] = 469,
  [SMALL_STATE(38)] = 474,
  [SMALL_STATE(39)] = 479,
  [SMALL_STATE(40)] = 484,
  [SMALL_STATE(41)] = 491,
  [SMALL_STATE(42)] = 498,
  [SMALL_STATE(43)] = 502,
  [SMALL_STATE(44)] = 506,
  [SMALL_STATE(45)] = 510,
  [SMALL_STATE(46)] = 514,
  [SMALL_STATE(47)] = 518,
  [SMALL_STATE(48)] = 522,
  [SMALL_STATE(49)] = 526,
  [SMALL_STATE(50)] = 530,
  [SMALL_STATE(51)] = 534,
  [SMALL_STATE(52)] = 538,
  [SMALL_STATE(53)] = 542,
  [SMALL_STATE(54)] = 546,
  [SMALL_STATE(55)] = 550,
  [SMALL_STATE(56)] = 554,
  [SMALL_STATE(57)] = 558,
  [SMALL_STATE(58)] = 562,
  [SMALL_STATE(59)] = 566,
  [SMALL_STATE(60)] = 570,
  [SMALL_STATE(61)] = 574,
  [SMALL_STATE(62)] = 578,
  [SMALL_STATE(63)] = 582,
  [SMALL_STATE(64)] = 586,
  [SMALL_STATE(65)] = 590,
  [SMALL_STATE(66)] = 594,
  [SMALL_STATE(67)] = 598,
  [SMALL_STATE(68)] = 602,
  [SMALL_STATE(69)] = 606,
  [SMALL_STATE(70)] = 610,
  [SMALL_STATE(71)] = 614,
  [SMALL_STATE(72)] = 618,
  [SMALL_STATE(73)] = 622,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_declaration, 3, 0, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraints_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraints_block_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_agent_body_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_directive, 3, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_declaration, 4, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 5, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_body, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraints_block, 6, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_block, 6, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_flow_block_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_block_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_system_directive, 3, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_expect, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_input, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_expect, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_step, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_text, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [173] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_text, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_level, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__indent] = true,
  },
  [3] = {
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_hmn_external_scanner_create(void);
void tree_sitter_hmn_external_scanner_destroy(void *);
bool tree_sitter_hmn_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_hmn_external_scanner_serialize(void *, char *);
void tree_sitter_hmn_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hmn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_hmn_external_scanner_create,
      tree_sitter_hmn_external_scanner_destroy,
      tree_sitter_hmn_external_scanner_scan,
      tree_sitter_hmn_external_scanner_serialize,
      tree_sitter_hmn_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "hmn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
